name = "webhook-gateway-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# Only need n8n backend in simplified setup
N8N_BACKEND = "https://n8n.pizeonicktech1818.dpdns.org"